version: '3.7'
services:
  web:
    build: .
    volumes:
      - ./PC-Automate:/var/www/html
    ports:
      - 80:80

  db:
    image: mysql
    volumes:
      - ./db:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
